n1=250 o1=-2.200000047683716 d1=0.03999999910593033 label1=''
n2=842 o2=-2.200000047683716 d2=0.03999999910593033 label2=''
n3=1 o3=0.0 d3=1.0
in='/net/friday/scr2/gbarnier/bpEttore40-fwime-3-9-dipole-s0e1-it75-s1fe5-it55-s3fe5-noSpline-e5-dask-re-re-re_inv_mod.H@'
esize=4
data_format="native_float"


Cp:   gbarnier@friday   Thu May 26 18:05:15 2022
		sets next: in="/net/vision/scr1/gbarnier/junk0.H@"
		copy_intag="bpEttore40-fwime-3-9-dipole-s0e1-it75-s1fe5-it55-s3fe5-noSpline-e5-dask-re-re-re/bpEttore40-fwime-3-9-dipole-s0e1-it75-s1fe5-it55-s3fe5-noSpline-e5-dask-re-re-re_inv_mod.H"
		data_format="native_float"


Window3d:   gbarnier@friday   Thu May 26 18:05:15 2022
		sets next: in="./vel_paper/BP_North_Sea_fwi_vel_paper.H@"
#Window #f1=55  #j1=1 #n1=140
#Window #f2=55  #j2=1 #n2=728
		junkME=0
	n2=728  o2=0.000000  d2=0.040000   unit2="Undefined"
		gff="-1"
		hff="-1"
hff=-1 gff=-1  n3=1  n4=1  n5=1  n6=1  n7=1  n8=1  n9=1
	n1=140  o1=0.000000  d1=0.040000   unit1="Undefined"
		hff="-1"
		gff="-1"
		esize=4
		data_format="native_float"
