in=/net/vision/scr1/ettore/syncline_true.H@
n1=129
o1=0
d1=2.500000e-02
n2=509
o2=0
d2=2.500000e-02


Cp:   gbarnier@vision   Mon Aug 26 13:36:41 2019
		sets next: in="/net/vision/scr1/gbarnier/VirieuxVelTrueOriginal.H@"
		copy_intag="/homes/sep/ettore/research/miscellaneous/Syncline/syncline_true.H"
		data_format="xdr_float"


Window3d:   gbarnier@storm.stanford.edu   Tue Aug 27 09:11:51 2019
		sets next: in="/net/storm/scr1/gbarnier/junk1.H@"
#Window #f1=0  #j1=2 #n1=65
#Window #f2=0  #j2=2 #n2=255
		junkME=0
	n2=255  o2=0.000000  d2=0.050000   label2="Undefined"   unit2="Undefined"
		gff="-1"
		hff="-1"
hff=-1 gff=-1  n3=1  n4=1  n5=1  n6=1  n7=1  n8=1  n9=1
	n1=65  o1=0.000000  d1=0.050000   label1="Undefined"   unit1="Undefined"
		hff="-1"
		gff="-1"
		esize=4
		data_format="xdr_float"



Pad:   gbarnier@storm.stanford.edu   Tue Aug 27 09:11:52 2019
		sets next: in="./vel_non_repro/Syncline-velTrue.H@"
	 	n1=105 o1=0 d1=0.05 label1=""

		#end=40
	 	n2=255 o2=0 d2=0.05 label2=""

		data_format="xdr_float"
