n1=218 o1=-2.75 d1=0.05000000074505806 label1='Undefined'
n2=474 o2=-5.25 d2=0.05000000074505806 label2='Undefined'
in='/net/storm/scr2/gbarnier/fwi-1-6-50m-dipole-lbfgs_inv_mod.H@'
data_format='xdr_float'
esize=4


Window3d:   gbarnier@jarvis   Thu May 26 12:28:36 2022
		sets next: in="./vel_paper/Syncline_fwi_vel_paper.H@"
#Window #f1=55  #j1=1 #n1=70
#Window #f2=105  #j2=1 #n2=255
		junkME=0
	n2=255  o2=0.000000  d2=0.050000   label2="Undefined"   unit2="Undefined"
		gff="-1"
		hff="-1"
hff=-1 gff=-1  n3=1  n4=1  n5=1  n6=1  n7=1  n8=1  n9=1
	n1=70  o1=0.000000  d1=0.050000   label1="Undefined"   unit1="Undefined"
		hff="-1"
		gff="-1"
		esize=4
		data_format="xdr_float"
