

:   gbarnier@friday   Fri Oct 15 21:48:03 2021
	 	n1=298 o1=-2.75 d1=0.05 label1=""

	 	n2=922 o2=-2.75 d2=0.05 label2=""

	 	n3=1 o3=0 d3=1 label3="none"

	 	n4=1 o4=0 d4=1 label4="none"

	 	n5=1 o5=0 d5=1 label5="none"

	 	n6=1 o6=0 d6=1 label6="none"

	 	n7=1 o7=0 d7=1 label7="none"

	 	n8=1 o8=0 d8=1 label8="none"

		esize=4
		sets next: in="/net/friday/scr1/gbarnier/temp5.H@"
		data_format="xdr_float"


Window3d:   gbarnier@friday   Fri Oct 15 21:48:03 2021
		sets next: in="./vel_non_repro/BP_West_Africa-initVel1.H@"
#Window #f1=55  #j1=1 #n1=180
#Window #f2=55  #j2=1 #n2=800
		junkME=0
	n2=800  o2=0.000000  d2=0.050000   unit2="Undefined"
		gff="-1"
		hff="-1"
hff=-1 gff=-1  n3=1  n4=1  n5=1  n6=1  n7=1  n8=1  n9=1
	n1=180  o1=0.000000  d1=0.050000   unit1="Undefined"
		hff="-1"
		gff="-1"
		esize=4
		data_format="xdr_float"
